pipeline:
  build-linux:
    image: node:latest
    commands:
      - echo "Building for Linux..."
  build-macos:
    image: node:latest
    commands:
      - echo "Building for macOS..."
  build-windows:
    image: node:latest
    commands:
      - echo "Building for Windows..."
