pipeline:
  build:
    image: fedora:latest
    commands:
      - dnf install -y nodejs
      # - curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm install --no-frozen-lockfile
      - pnpm tauri build
